stages:
  - build

build-gcc:
  image: mapret/cppimage:v2
  stage: build
  script:
    - g++ --version
    - mkdir build
    - cmake -G="Ninja Multi-Config" -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_CXX_COMPILER=g++ -S . -B build
    - cmake --build build --config Release
    - cmake --build build --config Debug
  artifacts:
    paths:
      - build/Release/gpupdf
      - build/Debug/gpupdf
    expire_in: 1 week

build-clang:
  image: mapret/linux-clang:v1
  stage: build
  script:
    - clang++ --version
    - mkdir build
    - cmake -G="Ninja Multi-Config" -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_CXX_COMPILER=clang++ -S . -B build
    - cmake --build build --config Release
    - cmake --build build --config Debug
  artifacts:
    paths:
      - build/Release/gpupdf
      - build/Debug/gpupdf
    expire_in: 1 week

build-msvc:
  tags:
    - saas-windows-medium-amd64
  stage: build
  script:
    - mkdir build
    - cmake -S . -B build
    - cmake --build build --config Release
    - cmake --build build --config Debug
  artifacts:
    paths:
      - build/Release/gpupdf.exe
      - build/Debug/gpupdf.exe
    expire_in: 1 week
