image: mapret/cppimage:v2

stages:
  - build

build:
  stage: build
  script:
    - g++ --version
    - mkdir build
    - cmake -G="Ninja Multi-Config" -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_CXX_COMPILER=g++ -S . -B build
    - cmake --build build --config Release
    - cmake --build build --config Debug
  artifacts:
    paths:
      - build/Release/gpupdf
      - build/Debug/gpupdf
    expire_in: 1 week
